force-app/main/default/objects/CSR__c/CSR__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>New</actionName>
        <content>csr_CreateCSROverride</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>LightningComponent</type>
    </actionOverrides-->
    <description>CSR Header</description>
    <label>CSR</label>
    <nameField>
        <displayFormat>CSR-{0000}</displayFormat>
        <label>CSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSR__c/fields/csr_AccountId__c.field-meta.xml
<CustomField>
    <fullName>csr_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CSRs</relationshipLabel>
    <relationshipName>CSRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>csr_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CSR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Competitive_Type__c.field-meta.xml
<CustomField>
    <fullName>csr_Competitive_Type__c</fullName>
    <label>Competitive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Wholesale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Country__c.field-meta.xml
<CustomField>
    <fullName>csr_Country__c</fullName>
    <label>Country</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>csr_Currency_Code__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>CND</fullName>
            </value>
            <value>
                <fullName>PES</fullName>
            </value>
            <value>
                <fullName>PSO</fullName>
            </value>
            <value>
                <fullName>EUO</fullName>
            </value>
            <value>
                <fullName>COP</fullName>
            </value>
            <value>
                <fullName>RUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>csr_Customer_Name__c</fullName>
    <description>This field is only used to capture the Customer Name from dealer on the Community Case forms</description>
    <label>Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Dealer_Action__c.field-meta.xml
<CustomField>
    <fullName>csr_Dealer_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>csr_Dealer_Name__c</fullName>
    <label>Dealer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Dealer_Type__c.field-meta.xml
<CustomField>
    <fullName>csr_Dealer_Type__c</fullName>
    <label>Dealer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <default>true</default>
                <label>Group</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Store</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_DealerCode__c.field-meta.xml
<CustomField>
    <fullName>csr_DealerCode__c</fullName>
    <label>Dealer Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_DealerDivision__c.field-meta.xml
<CustomField>
    <fullName>csr_DealerDivision__c</fullName>
    <label>Dealer Division</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_DealerGroup__c.field-meta.xml
<CustomField>
    <fullName>csr_DealerGroup__c</fullName>
    <label>Dealer Group</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_District__c.field-meta.xml
<CustomField>
    <fullName>csr_District__c</fullName>
    <label>District</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_DPM_Name__c.field-meta.xml
<CustomField>
    <fullName>csr_DPM_Name__c</fullName>
    <label>DPM Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>csr_Effective_Date__c</fullName>
    <label>Effective Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>csr_Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Expedite__c.field-meta.xml
<CustomField>
    <fullName>csr_Expedite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expedite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>csr_Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Internal_Checkbox__c.field-meta.xml
<CustomField>
    <fullName>csr_Internal_Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/CSR_Number__c.field-meta.xml
<CustomField>
    <fullName>CSR_Number__c</fullName>
    <description>CSR Number / Header Promo Code</description>
    <label>CSR#</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Phase__c.field-meta.xml
<CustomField>
    <fullName>csr_Phase__c</fullName>
    <label>Phase</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Region__c.field-meta.xml
<CustomField>
    <fullName>csr_Region__c</fullName>
    <label>Region</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_RSM_Name__c.field-meta.xml
<CustomField>
    <fullName>csr_RSM_Name__c</fullName>
    <label>RSM Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Status__c.field-meta.xml
<CustomField>
    <fullName>csr_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Development</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Posted and Expired Date</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Posting in Process</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Pending PPD Response</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Posted</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Denied</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Submitted with Unvetted Competitor</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Dealer Action Required</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Routing</label>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>Holding</label>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR__c/fields/csr_Type__c.field-meta.xml
<CustomField>
    <fullName>csr_Type__c</fullName>
    <label>CSR Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Competitive</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Blind</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Wreck</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/csr_CSRSelector.cls
public class csr_CSRSelector {
    
    public static CSR__c getCSRById(Id csrId) {
        
        return [
            SELECT Id, CSR_Number__c, csr_Phase__c, csr_Type__c, csr_Competitive_Type__c,
            csr_Effective_Date__c, csr_Expiration_Date__c, csr_DealerCode__c, csr_DealerGroup__c, csr_Dealer_Type__c,
            csr_Dealer_Name__c, csr_DealerDivision__c, csr_Customer_Name__c, csr_Assigned_To__c,
            csr_Internal_Checkbox__c, csr_Status__c, CreatedDate, CreatedById, csr_AccountId__c,CreatedBy.Name,CreatedBy.FirstName,csr_Currency_Code__c,csr_District__c,csr_Region__c,
            csr_DPM_Name__c,csr_Exchange_Rate__c,csr_Country__c,csr_RSM_Name__c, csr_Expedite__c,csr_Dealer_Action__c
            FROM CSR__c
            WHERE Id = :csrId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }
    public static List<CSR__c> getExistingCSRByNumberAndPhase(String csrNumber, String phase) {
        return [
            SELECT Id, CSR_Number__c, csr_Phase__c
            FROM CSR__c
            WHERE CSR_Number__c = :csrNumber
            AND csr_Phase__c = : (String.isNotBlank(phase) ? Decimal.valueOf(phase) : null)
            LIMIT 1
        ];
    }
    
    /**
* Fetch CSR__c records by CSR Numbers.
*/
    public static List<CSR__c> getCsrsByCsrNumberAndPhases(Set<String> csrNumbers, Set<Decimal> csrPhases) {
        return [
            SELECT Id,
            CSR_Number__c,
            CSR_Phase__c,
            CSR_Expedite__c,
            CSR_Status__c,
            CreatedDate
            FROM CSR__c
            WHERE CSR_Number__c IN :csrNumbers
            AND CSR_Phase__c IN : csrPhases
            WITH SECURITY_ENFORCED
        ];
    }
    
    /**
* Fetch a single CSR__c record Id by CSR Number.
*/
    public static List<CSR__c> getCsrIdByNumber(String csrNumber) {
        return [
            SELECT Id, CSR_Number__c
            FROM CSR__c
            WHERE CSR_Number__c = :csrNumber
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }
    
    
    public static CSR__c getCSRByNumberAndPhase(String csrNumber, Integer phase) {
        return [
            SELECT Id, csr_Status__c
            FROM CSR__c
            WHERE CSR_Number__c = :csrNumber
            AND csr_Phase__c = :phase
            WITH SECURITY_ENFORCED
            LIMIT 1   
        ];
    }
}