force-app/main/default/objects/CSR__c/CSR__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>New</actionName>
        <content>csr_CreateCSROverride</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>LightningComponent</type>
    </actionOverrides-->
    <description>CSR Header</description>
    <label>CSR</label>
    <nameField>
        <displayFormat>CSR-{0000}</displayFormat>
        <label>CSR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSR__c/fields/csr_Status__c.field-meta.xml
<CustomField>
    <fullName>csr_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Development</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Posted and Expired Date</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Posting in Process</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Pending PPD Response</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Posted</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Denied</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Submitted with Unvetted Competitor</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Dealer Action Required</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Routing</label>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>Holding</label>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR_Line__c/CSR_Line__c.object-meta.xml
<CustomObject>
    <label>CSR Line</label>
    <nameField>
        <label>Line#</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSR Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSR_Line__c/fields/CSR__c.field-meta.xml
<CustomField>
    <fullName>CSR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSR</label>
    <referenceTo>CSR__c</referenceTo>
    <relationshipLabel>CSR Lines</relationshipLabel>
    <relationshipName>CSR_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Best_Net__c.field-meta.xml
<CustomField>
    <fullName>csr_Best_Net__c</fullName>
    <label>Best Net</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Cancel_Reason__c.field-meta.xml
<CustomField>
    <fullName>csr_Cancel_Reason__c</fullName>
    <label>Cancel Reason</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Competitor__c.field-meta.xml
<CustomField>
    <fullName>csr_Competitor__c</fullName>
    <description>Competitor</description>
    <label>Competitor</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Competitor_Brand__c.field-meta.xml
<CustomField>
    <fullName>csr_Competitor_Brand__c</fullName>
    <label>Competitor Brand</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Competitor_P_N__c.field-meta.xml
<CustomField>
    <fullName>csr_Competitor_P_N__c</fullName>
    <label>Competitor P/N</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Competitor_Price__c.field-meta.xml
<CustomField>
    <fullName>csr_Competitor_Price__c</fullName>
    <description>Competitor Price</description>
    <label>Competitor Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Discount__c.field-meta.xml
<CustomField>
    <fullName>csr_Discount__c</fullName>
    <label>Discount</label>
    <precision>11</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Exception_Comment__c.field-meta.xml
<CustomField>
    <fullName>csr_Exception_Comment__c</fullName>
    <description>Field to store Exception Comment</description>
    <label>Exception Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Landing_Cost__c.field-meta.xml
<CustomField>
    <fullName>csr_Landing_Cost__c</fullName>
    <description>csr_Landing_Cost</description>
    <label>Landing Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Marketing_Review__c.field-meta.xml
<CustomField>
    <fullName>csr_Marketing_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Part_Description__c.field-meta.xml
<CustomField>
    <fullName>csr_Part_Description__c</fullName>
    <label>Part Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Part_Type__c.field-meta.xml
<CustomField>
    <fullName>csr_Part_Type__c</fullName>
    <label>Part Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Part_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>csr_Part_Type_Description__c</fullName>
    <label>Part Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Parts_Number__c.field-meta.xml
<CustomField>
    <fullName>csr_Parts_Number__c</fullName>
    <label>Parts Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_PPD_MRG__c.field-meta.xml
<CustomField>
    <fullName>csr_PPD_MRG__c</fullName>
    <label>PPD MRG</label>
    <precision>11</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/Csr_Price__c.field-meta.xml
<CustomField>
    <fullName>Csr_Price__c</fullName>
    <label>CSR Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Pricing_Alert__c.field-meta.xml
<CustomField>
    <fullName>csr_Pricing_Alert__c</fullName>
    <description>Field to store Pricing Alerts</description>
    <label>Pricing Alert</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Quantity__c.field-meta.xml
<CustomField>
    <fullName>csr_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Requested_Discount__c.field-meta.xml
<CustomField>
    <fullName>csr_Requested_Discount__c</fullName>
    <description>csr_Requested_Discount</description>
    <label>Requested Discount</label>
    <precision>11</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Status__c.field-meta.xml
<CustomField>
    <fullName>csr_Status__c</fullName>
    <description>These are csr line status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Development</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Posted and Expired Date</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Posting in Process</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Pending PPD Response</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Posted</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Denied</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Submitted with Unvetted Competitor</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Dealer Action Required</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Routing</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Holding</label>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_STDDLERNET__c.field-meta.xml
<CustomField>
    <fullName>csr_STDDLERNET__c</fullName>
    <description>csr_STDDLERNET</description>
    <label>STDDLERNET</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_Stock_Class__c.field-meta.xml
<CustomField>
    <fullName>csr_Stock_Class__c</fullName>
    <label>Stock Class</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Line__c/fields/csr_W_D__c.field-meta.xml
<CustomField>
    <fullName>csr_W_D__c</fullName>
    <label>W/D</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHS</fullName>
            </value>
            <value>
                <fullName>DSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/csr_CSRLineSelector.cls
public with sharing class csr_CSRLineSelector{
    
    /**
* Get CSR Lines by Ids
*/
    public static Map<Id, CSR_Line__c> getCSRlinesByIds(Set<Id> lineIds) {        
        
        return new Map<Id, CSR_Line__c>([
            SELECT Id, Name, csr_Part_Type__c, csr_Part_Description__c, csr_Discount__c, 
            Csr_Price__c, csr_Competitor_Price__c, csr_Competitor_P_N__c, csr_Competitor_Brand__c, 
            csr_Competitor__c, csr_Best_Net__c, csr_W_D__c, csr_Stock_Class__c, csr_Requested_Discount__c, 
            csr_Quantity__c, csr_Parts_Number__c, csr_PPD_MRG__c, csr_Landing_Cost__c, 
            csr_STDDLERNET__c, csr_Part_Type_Description__c, csr_Status__c,CSR__c,csr_Cancel_Reason__c,csr_Marketing_Review__c,
            csr_Exception_Comment__c,csr_Pricing_Alert__c
 
            FROM CSR_Line__c
            WHERE Id IN :lineIds
            WITH SECURITY_ENFORCED
        ]);
    }
    
    /**
* Get CSR Lines by CSR Case Id
*/
    public static List<CSR_Line__c> getCSRlinesByCSRId(Id csrId) {
        
        
        return [
            SELECT Id, Name, csr_Part_Type__c, csr_Part_Description__c, csr_Discount__c, Csr_Price__c, 
            csr_Competitor_Price__c, csr_Competitor_P_N__c, csr_Competitor_Brand__c, csr_Competitor__c, 
            csr_Best_Net__c, csr_W_D__c, csr_Stock_Class__c, csr_Requested_Discount__c, csr_Quantity__c, 
            csr_Parts_Number__c, csr_PPD_MRG__c, csr_Landing_Cost__c, csr_STDDLERNET__c, 
            csr_Part_Type_Description__c, csr_Status__c,CSR__c,csr_Marketing_Review__c,csr_Cancel_Reason__c,
            csr_Exception_Comment__c,csr_Pricing_Alert__c
            FROM CSR_Line__c
            WHERE CSR__c = :csrId
            WITH SECURITY_ENFORCED
            ORDER BY Createddate ASC
        ];
    }
    
    /**
* Get CSR Lines to delete
*/
    public static List<CSR_Line__c> getForDelete(List<Id> recordIds) {        
        
        return [
            SELECT Id 
            FROM CSR_Line__c 
            WHERE Id IN :recordIds
            WITH SECURITY_ENFORCED
        ];
    }

  public static List<CSR_Line__c> getCSRLinesWherePartNumberChannelAndQuantityIsNotNull(Id csrId) {
        return [
            SELECT Id, csr_Parts_Number__c, csr_W_D__c, csr_Quantity__c
            FROM CSR_Line__c
            WHERE CSR__c = :csrId
            AND csr_Parts_Number__c != null
            AND csr_W_D__c != null
            AND csr_Quantity__c!=null
        ];
    }
public static List<CSR_Line__c> getCSRLinesByCSRIdAndLineNumbers(Id csrId, List<String> lineNumbers) {
        return [
            SELECT Id, csr_Status__c
            FROM CSR_Line__c
            WHERE CSR__c = :csrId
            AND Name IN :lineNumbers
            WITH SECURITY_ENFORCED
        ];
    }


    public static Integer countActiveLinesByCSRId(Id csrId) {
        return [
            SELECT COUNT()
            FROM CSR_Line__c
            WHERE CSR__c = :csrId
            AND csr_Status__c != 'T'
            WITH SECURITY_ENFORCED
        ];
    }

}