force-app/main/default/objects/eDealer_Log__c/eDealer_Log__c.object-meta.xml
<CustomObject>
    <label>eDealer Log</label>
    <nameField>
        <displayFormat>Log-{000}</displayFormat>
        <label>Dealer Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eDealer Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/eDealer_Log__c/fields/Apex_Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Apex_Exception_Message__c</fullName>
    <label>Apex Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/eDealer_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cache API Response</fullName>
            </value>
            <value>
                <fullName>Apex Exception</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>API Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EdealerDeleteOldLogsBatchTest.cls
@isTest
public class EdealerDeleteOldLogsBatchTest {
    
    @isTest
    private static void testBatch(){
        
        //log
        eDealer_Log__c oldLog = new eDealer_Log__c();
        oldLog.Log_Type__c = 'API Error';
        oldLog.Apex_Exception_Message__c = 'error';
        
        insert oldLog;
        System.assertEquals('API Error', [SELECT Log_Type__c FROM eDealer_Log__c LIMIT 1].Log_Type__c, 'Unexpected Dealer logs.');
        
        Test.setCreatedDate(oldLog.id, Datetime.now().addDays(-16));
        
        Test.startTest();
        EdealerDeleteOldLogsBatch objBatch=new EdealerDeleteOldLogsBatch();
        Id jobid = Database.executeBatch(objBatch);
        String sch = '0 0 3 * * ?';
        system.schedule('Test edealer logs delete batch', sch, objBatch); 
        Test.stopTest();
        
        System.assert(jobid != null, 'Job execution is failed.');
    }

}