force-app/main/default/objects/CSR_Template_Notification__mdt/CSR_Template_Notification__mdt.object-meta.xml
<CustomObject>
    <description>CSR Mass Upload Template Notification</description>
    <label>CSR Template Notification</label>
    <pluralLabel>CSR Template Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/CSR_Template_Notification__mdt/fields/CSR_Template_End_Date__c.field-meta.xml
<CustomField>
    <fullName>CSR_Template_End_Date__c</fullName>
    <description>CSR Mass Upload Template Announcement End Date</description>
    <inlineHelpText>CSR Mass Upload Template Announcement End Date</inlineHelpText>
    <label>CSR Template End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSR_Template_Notification__mdt/fields/CSR_Template_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>CSR_Template_Start_Date__c</fullName>
    <description>CSR Mass Upload Template Announcement Start Date</description>
    <inlineHelpText>CSR Mass Upload Template Announcement Start Date</inlineHelpText>
    <label>CSR Template Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EDealerCSRTemplateAnnouncement.cls
public with sharing class EDealerCSRTemplateAnnouncement {
    @AuraEnabled(cacheable=true)  

	public static CSR_Template_Notification__mdt getTemplateDetail() {
    
    	        return [ 
                        SELECT Id, CSR_Template_Start_Date__c, CSR_Template_End_Date__c
                        FROM CSR_Template_Notification__mdt 
                        where DeveloperName ='CSR_Template_Announcement' 
                        LIMIT 1
                ];
	}

    @AuraEnabled(cacheable=true)
    public static CSRAnnouncement getCSRAnnouncementTranslations() {
        Map<String, String> message = getMessageTranslationValue('CSRAnnouncement');
        System.debug('Message '+message);
        return new CSRAnnouncement(message);
    }    
    
    static Map<String, String> getMessageTranslationValue(String attributeName){
        Map<String, String> options = new Map<String, String>();
        Map<String, Object> CSRAnnouncementTranslations = EDealerMetadataUtility.csrAnnouncementTranslations;
        system.debug('CSRAnnouncementTranslations '+CSRAnnouncementTranslations);

        Object allLanguageTranslations = CSRAnnouncementTranslations.get(attributeName);
        system.debug('allLanguageTranslations '+allLanguageTranslations);

        Map<String, object> convertedAttributes = (Map<String, object>) allLanguageTranslations;
        String translationLabel = (String) convertedAttributes.get(UserInfo.getLanguage());
        options.put('label', translationLabel);
        system.debug('Option value '+options);
        return options;
    }

    public class CSRAnnouncement {
        @AuraEnabled
        public Map<String, String> message;
        public CSRAnnouncement(Map<String, String> message) {
            this.message = message;
        }
    } 
   

}