force-app/main/default/objects/Account/fields/Billing_Method__c.field-meta.xml
<CustomField>
    <fullName>Billing_Method__c</fullName>
    <label>Billing Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO from Dealer</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>PPFS Instant Reimbursement</fullName>
            </value>
            <value>
                <fullName>Instant Reimbursement</fullName>
            </value>
            <value>
                <fullName>PPFS (KW &amp; PB Fleet)</fullName>
            </value>
            <value>
                <fullName>PPFS Standard Payment</fullName>
            </value>
            <value>
                <fullName>Standard Payment</fullName>
            </value>
            <value>
                <fullName>Pending EFT</fullName>
            </value>
            <value>
                <fullName>PPFS EFT</fullName>
            </value>
            <value>
                <fullName>PPFS Hard Check</fullName>
            </value>
            <value>
                <fullName>Customer Pay Direct</fullName>
            </value>
            <value>
                <fullName>Access Account</fullName>
            </value>
            <value>
                <fullName>Warranty/Other</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>80% Credit Hold</fullName>
            </value>
            <value>
                <fullName>PPFS (GOP)</fullName>
            </value>
            <value>
                <fullName>KW &amp; PB Fleet Acct (Cust Pay)</fullName>
            </value>
            <value>
                <fullName>Customer Pays Directly at ISPs and Dealers</fullName>
            </value>
            <value>
                <fullName>Fleet Account where PCC Pays ISPs and issues PO at Dealers</fullName>
            </value>
            <value>
                <fullName>Fleet Account where PCC Pays ISPs and Customer issues PO at Dealers</fullName>
            </value>
            <value>
                <fullName>Fleet Account where Customer Pays ISPs and issues PO at Dealers</fullName>
            </value>
            <value>
                <fullName>Virtual Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Deposit</fullName>
            </value>
            <value>
                <fullName>Credit Card Over the Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Preferred Currency for payment</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_ISP_PPFS_ID__c.field-meta.xml
<CustomField>
    <fullName>Dealer_ISP_PPFS_ID__c</fullName>
    <label>Dealer ISP PPFS ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fleet_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Account_Code__c</fullName>
    <label>Fleet Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Fleet__c.field-meta.xml
<CustomField>
    <fullName>Is_Fleet__c</fullName>
    <description>Flag is Account is a &quot;Fleet&quot; account.</description>
    <formula>AND(
OR(
LEFT(Account_Code__c, 2) = &apos;FL&apos;,
LEFT(Account_Code__c, 2) = &apos;CU&apos;
),
OR(
ISPICKVAL(Type, &apos;Customer&apos;) ,
ISPICKVAL(Type, &apos;Fleet&apos;)
)
)</formula>
    <label>Is Fleet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Paclease__c.field-meta.xml
<CustomField>
    <fullName>Is_Paclease__c</fullName>
    <description>Determines if Account is classified as a Paclease account</description>
    <formula>LEFT(Account_Code__c, 2) = &apos;PL&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Paclease</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <label>Legal Name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Type__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Tax Identification Number</fullName>
            </value>
            <value>
                <fullName>Social Security Number</fullName>
            </value>
            <value>
                <fullName>Federal Employer Identification Number</fullName>
            </value>
            <value>
                <fullName>Tax Identification Number</fullName>
            </value>
            <value>
                <fullName>Social Insurance Number</fullName>
            </value>
            <value>
                <fullName>Business Number</fullName>
            </value>
            <value>
                <fullName>Goods and Services Tax</fullName>
            </value>
            <value>
                <fullName>Quebec Sales Tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Independent_Service_Provider.recordType-meta.xml
<RecordType>
    <fullName>Independent_Service_Provider</fullName>
    <active>true</active>
    <description>ISPs</description>
    <label>Independent Service Provider</label>
</RecordType>

force-app/main/default/objects/Account_PASSCompany_Xref__c/Account_PASSCompany_Xref__c.object-meta.xml
<CustomObject>
    <label>Account-PASSCompany-Xref</label>
    <nameField>
        <label>Account-PASSCompany-Xref Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account-PASSCompanies-Xref</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_PASSCompany_Xref__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account-PASSCompanies-Xref</relationshipLabel>
    <relationshipName>Account_PASSCompanies_Xref</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_PASSCompany_Xref__c/fields/Company_UID__c.field-meta.xml
<CustomField>
    <fullName>Company_UID__c</fullName>
    <label>Company UID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <description>Dealer Code Field Referenced in Community Dashboards Security Predicate</description>
    <formula>Contact.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>MXN</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountDAO.cls
/**
 * @author anthony.beran@slalom.com
 * @date 2019-05-26
 * @version 1.0
 * @description AccountDAO
 */

public with sharing class AccountDAO {
    
    /**
    public static List<Account> getAccountByDealerCode(Set<String> dealerCodes) {
        return [
            SELECT Dealer_Code__c, Dealer_ISP_PPFS_ID__c, Billing_Method__c
            FROM Account
            WHERE Dealer_Code__c IN :dealerCodes
        ];
    }
    **/    
    // This is the method which is added as replacement of the above method
    // Now SAML will send the fleet code as well so we have to consider that is the query while reterving the account.
    public static List<Account> getAccountByDealerCode(Set<String> dealerCodes) {    
        
        // make the dealer code in like set so that we can use the like operator
        set<string> setLikeDealerCode = new set<string>();
        for(String strDealderCode : dealerCodes){
           
            setLikeDealerCode.add('%'+strDealderCode+'%');
        }
        
        //new requirement for fleet user changes        
        String accId = null;
        List<Account_PASSCompany_Xref__c> accList=[Select Account__c,Company_UID__C from Account_PASSCompany_Xref__c where Company_UID__C IN: dealerCodes];
        if(accList.size()>0){
          
             accId = accList[0].Account__c;                            
         }       

        return [
            SELECT Name,Dealer_Code__c, Dealer_ISP_PPFS_ID__c, Billing_Method__c,Fleet_Account_Code__c
            FROM Account
            WHERE (Dealer_Code__c IN :dealerCodes 
                    OR Id=: accId
                    ) 
        ];                
    }

    public static List<Account> getById(Set<Id> accountIds) {
        return [
            SELECT Id, Is_Fleet__c, Is_Paclease__c, Type
            FROM Account
            WHERE Id IN :accountIds
        ];
    }

    public static List<Account> getDealerInfo(Set<Id> accountIds) {
        return [
            SELECT Dealer_Code__c, Name, Legal_Name__c, Site, Type, PACCARDivision__c, Currency__c, Tax_Type__c, Tax_ID__c, (
                SELECT FirstName, LastName, MailingStreet, MailingCity, MailingPostalCode, MailingState, MailingCountry, Email, Phone, MailingAddress
                FROM Contacts
            )
            FROM Account
            WHERE Id IN :accountIds
        ];
    }

    public static List<Account> getISPDealersMissingId() {
        Datetime now = Datetime.now();

        return [
            SELECT Id
            FROM Account
            WHERE LastModifiedDate >= :now.addDays(-2)
            AND Dealer_ISP_PPFS_ID__c = NULL
            AND (
                RecordType.DeveloperName = 'Independent_Service_Provider'
                OR PaccarDivision__c = 'PacCentral'
            )
        ];
    }
    
    public static List<Account_PASSCompany_Xref__c> getAccountXref(Set<String> accId) {
       
        return [SELECT Account__c,Company_UID__C 
                FROM Account_PASSCompany_Xref__c 
                WHERE Company_UID__C IN: accId];    
    }
    
    public static List<Account> getAccountsByDealerCodes(Set<String> dealerCodes) {
        if (dealerCodes == null || dealerCodes.isEmpty()) {
            return new List<Account>();
        }
        
        return [
            SELECT Id, Dealer_Code__c
            FROM Account
            WHERE Dealer_Code__c IN :dealerCodes
        ];
    }
}