force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Fleet_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Account_Code__c</fullName>
    <label>Fleet Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <inlineHelpText>U001=KW West
U002=KW Central
U003=KW East
U004=PB West
U005=PB Central
U006=PB East
C001=KW Canada
C002=PB Canada
M001=Mexico
121=Gulf
131=Europe
133=Mexico
141=Africa
151=Asia-Pacific
16=China
171=Russia
181=South Am.
191=Central Am.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U001</fullName>
            </value>
            <value>
                <fullName>U002</fullName>
            </value>
            <value>
                <fullName>U003</fullName>
            </value>
            <value>
                <fullName>U004</fullName>
            </value>
            <value>
                <fullName>U005</fullName>
            </value>
            <value>
                <fullName>U006</fullName>
            </value>
            <value>
                <fullName>C001</fullName>
            </value>
            <value>
                <fullName>C002</fullName>
            </value>
            <value>
                <fullName>M001</fullName>
            </value>
            <value>
                <fullName>181</fullName>
            </value>
            <value>
                <fullName>191</fullName>
            </value>
            <value>
                <fullName>C004</fullName>
            </value>
            <value>
                <fullName>C003</fullName>
            </value>
            <value>
                <fullName>C005</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <formula>Account.Dealer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserUid__c.field-meta.xml
<CustomField>
    <fullName>UserUid__c</fullName>
    <description>This is unique user identifier from Click system. Used to match contact to user records when creating from Click sync job.</description>
    <label>UserUid</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/csr_Approver_Id__c.field-meta.xml
<CustomField>
    <fullName>csr_Approver_Id__c</fullName>
    <label>CSR Approver Id</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <description>Dealer Code Field Referenced in Community Dashboards Security Predicate</description>
    <formula>Contact.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/UserUid__c.field-meta.xml
<CustomField>
    <fullName>UserUid__c</fullName>
    <description>This is unique user identifier from Click system</description>
    <externalId>true</externalId>
    <label>UserUid</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UserDAO.cls
/**
 * @author anthony.beran@slalom.com
 * @date 2019-05-24
 * @version 1.0
 * @description UserDAO
 */

public with sharing class UserDAO {

    public static List<User> getById(Set<Id> ids) {
        return [
            SELECT UserUid__c, Username, Email, FirstName, LastName, Alias, IsActive, ContactId, IsPortalEnabled, Profile.Name, Contact.Account.Dealer_Code__c, Name
            FROM User
            WHERE Id IN :ids
        ];
    }

    public static List<User> getByUID(Set<String> uids) {
        return [
            SELECT profileid, 
                    CommunityNickname, 
                    UserUid__c, 
                    Username, 
                    Email, 
                    LastName, 
                    Alias, 
                    IsActive, 
                    ContactId, 
                    IsPortalEnabled, 
                    Contact.Account.Dealer_Code__c,                    
                    Contact.Account.Fleet_Account_Code__c,
                    LanguageLocaleKey
            FROM User
            WHERE UserUid__c IN :uids AND UserUid__c != null
        ];
    }

    public static List<User> getByAccount(Set<Id> accountIds) {
        return [
            SELECT IsPortalEnabled, IsActive
            FROM User
            WHERE User.Contact.AccountId IN :accountIds
        ];
    }

    public static List<User> getAccountInfo(Set<Id> ids) {
        return [
            SELECT Id, Contact.Account.PACCARDivision__c, Contact.Account.Name, Contact.Account.Region__c
            FROM User
            WHERE Id IN :ids
        ];
    }
    
    public static List<User> getAllUsersWithCSRAccess() {
        return [
            SELECT Id, Name
            FROM User
            WHERE IsActive = TRUE
            AND Id IN (
                SELECT AssigneeId
                FROM PermissionSetAssignment
                WHERE PermissionSet.Name = 'CSR_Processor'
            )
            WITH SECURITY_ENFORCED
            ORDER BY LastModifiedDate DESC
        ];
    }

    /**
     * Fetch CSR Approver Id for the current user.
     */
    public static Decimal getApproverIdForCurrentUser() {
        User u = [
            SELECT csr_Approver_Id__c
            FROM User
            WHERE Id = :UserInfo.getUserId()
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        return u.csr_Approver_Id__c;
    }
}