force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eDealer_Carrier__c/eDealer_Carrier__c.object-meta.xml
<CustomObject>
    <label>EDealer Carrier</label>
    <nameField>
        <label>EDealer Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EDealer Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EDealerLookupControllerTest.cls
@isTest
public class EDealerLookupControllerTest {
    
    @isTest
    private static void validateLookupContr(){
        Account objAccount =new Account(Dealer_Code__c='V648',Name='account',PACCARDivision__c='P');
        insert objAccount;
        
        List<eDealer_Carrier__c> carrierLst = new List<eDealer_Carrier__c>();
        eDealer_Carrier__c carrier = new eDealer_Carrier__c();
        carrier.Name = 'test Carrier';
        carrierLst.add(carrier);
        insert carrierLst;
        System.assertEquals('test Carrier',carrierLst[0].Name,'Name shold be "test Carrier".');
        
        Test.startTest();
        List < sObject > returnList1 = EDealerLookupController.fetchLookUpValues('Test','eDealer_Carrier__c');
        System.assert(returnList1.size()==1,'list size should be 1.');
        List < sObject > returnList2 = EDealerLookupController.fetchDealerLocValues('V648','account','p');
        System.assert(returnList2.size()==1,'list size should be 1.');
        Test.stopTest();
    }
    
}