force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group_Code__c</fullName>
    <label>Dealer Group Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group_Name__c</fullName>
    <label>Dealer Group Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <formula>Account.Dealer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/EDealer_Relationship__c.object-meta.xml
<CustomObject>
    <label>EDealer Relationship</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>EDealer Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDealer Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealer_Relationship__c/fields/Allow_Download_Of_Reports__c.field-meta.xml
<CustomField>
    <fullName>Allow_Download_Of_Reports__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Download Of Reports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Allow_Upload_Of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Allow_Upload_Of_Orders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Upload Of Orders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Allow_Upload_Of_Rma__c.field-meta.xml
<CustomField>
    <fullName>Allow_Upload_Of_Rma__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Upload Of Rma</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/ASI_Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>ASI_Dealer_Code__c</fullName>
    <label>ASI Dealer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Availability_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Availability_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EDealer Relationships</relationshipLabel>
    <relationshipName>EDealer_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Dealer_Control_Of_Doests__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Control_Of_Doests__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Control Of Doests</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Dealer_Doe_Status__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Doe_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Doe Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Dealer_Group__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group__c</fullName>
    <label>Dealer Group</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Interactive_Order_Entry__c.field-meta.xml
<CustomField>
    <fullName>Interactive_Order_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interactive Order Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Order_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Order_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Price_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Price_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Return_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Return_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Sub_Code__c.field-meta.xml
<CustomField>
    <fullName>Sub_Code__c</fullName>
    <label>Sub Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EDealer_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/ASI_Username__c.field-meta.xml
<CustomField>
    <fullName>ASI_Username__c</fullName>
    <label>ASI Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <description>Dealer Code Field Referenced in Community Dashboards Security Predicate</description>
    <formula>Contact.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/eDealerCSRViewCommentsControllerTest.cls
@IsTest
public class eDealerCSRViewCommentsControllerTest {
    
    @TestSetup static void createTestData() {
        Account account = new Account();
        account.Name = 'Test Account';
        account.Dealer_Code__c = 'I080';
        account.Dealer_Group_Name__c='test';
        account.Dealer_Group_Code__c='I080';
        account.PACCARDivision__c = 'K';
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer Groups and Dealerships').getRecordTypeId();
        insert account;
        
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Contact';
        contact.AccountId = account.Id;
        contact.Email = 'testing@nonemail.com';
        
        insert contact;
        
        EDealer_Relationship__c eDealerRel = new EDealer_Relationship__c();
        eDealerRel.Contact__c = contact.Id;
        eDealerRel.ASI_Dealer_Code__c = 'I080';
        eDealerRel.Sub_Code__c = '009';
        eDealerRel.Customer_Name__c = 'Testing EDealer Relationship';
        eDealerRel.Allow_Download_Of_Reports__c = true;
        eDealerRel.Allow_Upload_Of_Orders__c = true;
        eDealerRel.Allow_Upload_Of_Rma__c = true;
        eDealerRel.Availability_Inquiry__c = true;
        eDealerRel.Dealer_Control_Of_Doests__c = true;
        eDealerRel.Dealer_Doe_Status__c = true;
        eDealerRel.Interactive_Order_Entry__c = true;
        eDealerRel.Order_Inquiry__c = true;
        eDealerRel.Price_Inquiry__c = true;
        eDealerRel.Return_Inquiry__c = true;
        eDealerRel.Division__c = 'K';
        eDealerRel.Currency_Code__c = 'USD';
        eDealerRel.Dealer_Group__c = 'I080';
        eDealerRel.Dealer_Doe_Status__c = true;
        eDealerRel.Dealer_Doe_Status__c = true;
        insert eDealerRel;
        
        Profile profile = [SELECT Id FROM Profile WHERE Name='Paccar TCS edealer Community Plus']; 
        User user = new User();
        user.Alias = 'standt';
        user.Email = 'systemAdministrator@nonemail.com';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.FirstName = 'Testing';
        user.LastName = 'User';
        user.LanguageLocaleKey = 'en_US';
        user.ContactId=contact.Id;
        user.LocaleSidKey = 'en_US';
        user.ProfileId = profile.Id;
        user.ASI_Username__c='I080';
        user.TimeZoneSidKey = 'America/Los_Angeles';
        user.UserName = 'systemAdministrator@testorg.io';
        insert user;
        
        EDealer_Relationship__c eDealerRelForUser = new EDealer_Relationship__c();
        eDealerRelForUser.User__c = user.Id;
        eDealerRelForUser.ASI_Dealer_Code__c = 'I080';
        eDealerRelForUser.Sub_Code__c = '009';
        eDealerRelForUser.Customer_Name__c = 'EDealer Relationship for User';
        eDealerRelForUser.Allow_Download_Of_Reports__c = true;
        eDealerRelForUser.Allow_Upload_Of_Orders__c = true;
        eDealerRelForUser.Allow_Upload_Of_Rma__c = true;
        eDealerRelForUser.Availability_Inquiry__c = true;
        eDealerRelForUser.Dealer_Control_Of_Doests__c = true;
        eDealerRelForUser.Dealer_Doe_Status__c = true;
        eDealerRelForUser.Interactive_Order_Entry__c = true;
        eDealerRelForUser.Order_Inquiry__c = true;
        eDealerRelForUser.Price_Inquiry__c = true;
        eDealerRelForUser.Return_Inquiry__c = true;
        eDealerRelForUser.Division__c = 'K';
        eDealerRelForUser.Currency_Code__c = 'USD';
        eDealerRelForUser.Dealer_Group__c = 'I080';
        eDealerRelForUser.Dealer_Doe_Status__c = true;
        eDealerRelForUser.Dealer_Doe_Status__c = true;
        insert eDealerRelForUser;
        
    }
    
    @IsTest static void validateGetCsrCommentsFromAws() {
        String csrNumber = '30348092';
        String csrPhase = '1';
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        String responseData = eDealerCSRViewCommentsController.getCsrCommentsFromAws(csrNumber, csrPhase);
        
        Test.stopTest();
        
        Assert.isNotNull(responseData, 'CSR Comment retrieval fails.');
    }
    
    @IsTest static void validateGetCommentsColumnHeaders() {
        Test.startTest();
        List<Map<String,String>> columnHeader = eDealerCSRViewCommentsController.getCommentsColumnHeaders();
        Test.stopTest();
        
        Assert.isFalse(columnHeader.isEmpty(), 'No such column header founds.');
    }
    
    /**@IsTest static void validateFetchLoggedInUserDetailsWithAdmin() {
        User user = [SELECT Id,Profile.Name FROM User WHERE FirstName = 'Testing' AND LastName = 'User'];
        Profile p = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator'];
        
        System.runAs(user) {
            eDealerCSRViewCommentsController.UserWrapper userDetails = eDealerCSRViewCommentsController.fetchLoggedInUserDetails();
        }
    }**/
    
    @IsTest static void validateFetchLoggedInUserDetailsWithPortalUser() {
        List<EDealer_Relationship__c> lstDealerRelationships = new List<EDealer_Relationship__c>(); 
        User user = [SELECT Id,IsPortalEnabled,ContactId FROM User Where IsPortalEnabled = true and IsActive = true LIMIT 1];
        eDealerCSRViewCommentsController.UserWrapper userDetails;
        System.runAs(user) {            
            try {
                test.startTest();
                userDetails = eDealerCSRViewCommentsController.fetchLoggedInUserDetails();                
                test.stopTest();
                
                
                // Add assertions here if the method execution is expected to be successful
            } catch (AuraHandledException ex) {
                // This block will handle the AuraHandledException
                // Add assertions here to verify the behavior when the exception is thrown
                System.assertEquals('Script-thrown exception', ex.getMessage(), 'Unexpected exception message');
            }            
        }        
    }
    
    @IsTest static void validateAccessibleDealerLocs() {
        Id contactId = [SELECT Id FROM User LIMIT 1].Id;
        Boolean isPortalUser = false;        
        Test.startTest();
        List<EDealer_Relationship__c> eDealerRels = eDealerCSRViewCommentsController.getAccessibleDealerLocs(contactId, isPortalUser);
        Test.stopTest();
    }
    
    @IsTest static void validateNotAccessibleDealerLocs() {
        Id userId = [SELECT Id FROM User WHERE FirstName = 'Testing' AND LastName = 'User' LIMIT 1].Id;
        Boolean isPortalUser = false;
        
        Test.startTest();
        List<EDealer_Relationship__c> eDealerRels = eDealerCSRViewCommentsController.getAccessibleDealerLocs(userId, isPortalUser);
        Test.stopTest();        
    }
    
    class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setBody('{"Data": {}, "ErrorResponse": {"IsSuccess": "false", "ErrorMessages": [{"ErrorDescription": "Sample Error"}]}}');
            res.setStatusCode(200);
            return res;
        }
    }
    
}