force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group_Name__c</fullName>
    <label>Dealer Group Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Group_Code__c</fullName>
    <label>Dealer Group</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EdealerAccountUtils.cls
public with sharing class EdealerAccountUtils {
    
    public static List<String> getFieldsNames(){
        List<String> fieldsName = new List<String>();
        fieldsName.add('Name');
        fieldsName.add('Dealer_Code__c');
        fieldsName.add('Dealer_Group_Name__c');
        fieldsName.add('Group_Code__c');
        fieldsName.add('PACCARDivision__c');
        return fieldsName;
    }
    
    
    public static List<Account> getDealersAccount(Set<String> setDealerLocs){
        String query = 'SELECT Id, ';
        query += String.join( getFieldsNames(), ', ');
        query += ' FROM Account';
        query += ' WHERE Dealer_Code__c IN :setDealerLocs';
        
        //SOQL
        List<Account> lstDealerAccounts = Database.query(query);
        
        return lstDealerAccounts;
    }
    
    public static List<Account> getDealersAccountByGroup(Set<String> setDealerGroupName){
        String query = 'SELECT Id, ';
        query += String.join( getFieldsNames(), ', ');
        query += ' FROM Account';
        query += ' WHERE Group_Code__c IN :setDealerGroupName';
        
        //SOQL
        List<Account> lstDealerAccounts = Database.query(query);
        
        return lstDealerAccounts;
    }

}