force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Dealer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group_Name__c</fullName>
    <label>Dealer Group Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Group_Code__c</fullName>
    <label>Dealer Group</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <formula>Account.Dealer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/EDealer_Tracking__c.object-meta.xml
<CustomObject>
    <label>Gateway Tracking</label>
    <nameField>
        <displayFormat>Track-{000}</displayFormat>
        <label>Gateway Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gateway Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealer_Tracking__c/fields/Dealer_Group__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group__c</fullName>
    <formula>Owner:User.Contact.Account.Group_Code__c</formula>
    <label>Dealer Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Kenworth_User_Visited__c.field-meta.xml
<CustomField>
    <fullName>Kenworth_User_Visited__c</fullName>
    <label>Kenworth User Visited</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Peterbilt_User_Visited__c.field-meta.xml
<CustomField>
    <fullName>Peterbilt_User_Visited__c</fullName>
    <label>Peterbilt User Visited</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <description>Dealer Code Field Referenced in Community Dashboards Security Predicate</description>
    <formula>Contact.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Pass_Group_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Pass_Group_Permissions__c</fullName>
    <label>Pass Group Permissions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
            </value>
            <value>
                <fullName>General Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EdealerTrackingControllerTest.cls
@isTest
public class EdealerTrackingControllerTest {
    
    @testSetup
    private static void testSetup() {
        Id profCommunity = [SELECT Id FROM Profile where Name = 'Paccar TCS edealer Community Plus'].Id;
        List<Account> accounts = new List<Account>{new Account(Name='TestAccount', Dealer_Code__c='999990' ,Dealer_Group_Name__c='subz' ,Group_Code__c='C111',PACCARDivision__c='K'),
            new Account(Name='TestAccount2', Dealer_Code__c='999910' ,Dealer_Group_Name__c='subx' ,Group_Code__c='C121',PACCARDivision__c='P')};
                insert accounts; 
        
        List<Contact> contacts = new List<Contact>();
        for(Account acc : accounts){
            contacts.add(new Contact(LastName ='testCon'+acc.Name ,AccountId = acc.Id));
        }
        
        insert contacts;
        List<User> users = New List<User>{new User(alias = 'test123', email ='test123@noemail.com',
                                                   emailencodingkey = 'UTF-8', LastName = 'Testing',
                                                   Languagelocalekey='en_US', localesidkey='en_US',
                                                   ProfileId = profCommunity, country='United States',
                                                   IsActive = true, ContactId = contacts[0].Id,Pass_Group_Permissions__c = 'Field Service',
                                                   timezonesidkey='America/Los_Angeles', username='testKenworth@noemail.com'),
            new User(alias = 'test23', email ='test1234@noemail.com',
                     emailencodingkey = 'UTF-8', LastName = 'Testing',
                     Languagelocalekey='en_US', localesidkey='en_US',
                     ProfileId = profCommunity, country='United States',
                     IsActive = true, ContactId = contacts[1].Id,Pass_Group_Permissions__c = 'Field Service',
                     timezonesidkey='America/Los_Angeles', username='testP@noemail.com')};
                         insert users;
    }
    
    @isTest static void testInsertTrackingDetailsForPeterbiltUser(){
        User userP = [SELECT Id FROM User WHERE username='testP@noemail.com' LIMIT 1];
        Test.startTest();
        system.runAs(userP) {
            EdealerTrackingController.insertTrackingDetails('Test Track');
        }
        Test.stopTest();
        EDealer_Tracking__c eDealerTracking = [SELECT Id, Peterbilt_User_Visited__c,Dealer_Group__c 
                                               FROM EDealer_Tracking__c LIMIT 1];
        System.assertEquals(1,eDealerTracking.Peterbilt_User_Visited__c);
        System.assertEquals('C121',eDealerTracking.Dealer_Group__c);
    }
    
    @isTest static void testInsertTrackingDetailsForKenworthUser(){
        User userK = [SELECT Id FROM User WHERE username='testKenworth@noemail.com' LIMIT 1];
        Test.startTest();
        system.runAs(userK) {
            EdealerTrackingController.insertTrackingDetails('Test Track');
        }
        Test.stopTest();
        EDealer_Tracking__c eDealerTracking = [SELECT Id, Kenworth_User_Visited__c,Dealer_Group__c 
                                               FROM EDealer_Tracking__c LIMIT 1];
        System.assertEquals(1,eDealerTracking.Kenworth_User_Visited__c);
        System.assertEquals('C111',eDealerTracking.Dealer_Group__c);
    }
    
    @isTest static void testInsertTrackingDetailsToUpdateExistingRecordForPUser(){
        User userP = [SELECT Id FROM User WHERE username='testP@noemail.com' LIMIT 1];
        Test.startTest();
        system.runAs(userP) {
            EdealerTrackingController.insertTrackingDetails('Test Track');
            EdealerTrackingController.insertTrackingDetails('Test Track');
        }
        Test.stopTest();
        EDealer_Tracking__c eDealerTracking = [SELECT Id, Peterbilt_User_Visited__c,Dealer_Group__c 
                                               FROM EDealer_Tracking__c LIMIT 1];
        System.assertEquals(2,eDealerTracking.Peterbilt_User_Visited__c);
    }
    
    @isTest static void testInsertTrackingDetailsToUpdateExistingRecordForKUser(){
        User userK = [SELECT Id FROM User WHERE username='testKenworth@noemail.com' LIMIT 1];
        Test.startTest();
        system.runAs(userK) {
            EdealerTrackingController.insertTrackingDetails('Test Track');
            EdealerTrackingController.insertTrackingDetails('Test Track');
        }
        Test.stopTest();
        EDealer_Tracking__c eDealerTracking = [SELECT Id, Kenworth_User_Visited__c,Dealer_Group__c 
                                               FROM EDealer_Tracking__c LIMIT 1];
        System.assertEquals(2,eDealerTracking.Kenworth_User_Visited__c);
    }
    
    @isTest static void testUpdateTimeSpent(){
        User u = [SELECT Id FROM User WHERE username='testKenworth@noemail.com' LIMIT 1];
        Test.startTest();
        system.runAs(u) {
            EdealerTrackingController.insertTrackingDetails('Test Track');
            EdealerTrackingController.updateTimeSpent('Test Track',12);
        }
        Test.stopTest();
    }
    
}