force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/EDealer_Suggested_Order__c.object-meta.xml
<CustomObject>
    <label>Suggested Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Suggested Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/DBS_Type__c.field-meta.xml
<CustomField>
    <fullName>DBS_Type__c</fullName>
    <label>DBS Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <formula>Dealer_Location__r.Dealer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Dealer_Location__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dealer Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suggested Orders</relationshipLabel>
    <relationshipName>Suggested_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Is_Special_Order_Part__c.field-meta.xml
<CustomField>
    <fullName>Is_Special_Order_Part__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Special Order Part</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Part_Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Category_Type__c</fullName>
    <label>Part Category Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DSP</fullName>
            </value>
            <value>
                <fullName>DUAL</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
            <value>
                <fullName>ENG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Part_Description__c.field-meta.xml
<CustomField>
    <fullName>Part_Description__c</fullName>
    <label>Part Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Pricing_Detail__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Detail__c</fullName>
    <label>Pricing Detail</label>
    <length>80000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Suggested_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;SOF&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOF</fullName>
            </value>
            <value>
                <fullName>Master Inventory</fullName>
            </value>
            <value>
                <fullName>Part Availability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EDealerCart__c/EDealerCart__c.object-meta.xml
<CustomObject>
    <label>EDealerCart</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>EDealerCart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDealerCarts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealerCart__c/fields/Dealer_Location__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EDealerCarts</relationshipLabel>
    <relationshipName>EDealerCarts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EDealerCart__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emergency Order</fullName>
            </value>
            <value>
                <fullName>Stock Order</fullName>
            </value>
            <value>
                <fullName>DSP Order</fullName>
            </value>
            <value>
                <fullName>DSP Emergency Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EDealerCart__c/fields/Suggested_Order__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Order__c</fullName>
    <label>Suggested Order</label>
    <referenceTo>EDealer_Suggested_Order__c</referenceTo>
    <relationshipLabel>EDealerCarts</relationshipLabel>
    <relationshipName>EDealerCarts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EDealerCart__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;In Cart&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Cart</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EDealerCartUtils.cls
/*** 
 * Name        :   EDealerCartUtils
 *  Description :   This is a Utility class for Cart Object. (Bascally will used for Query cart data )
 */ 
public without sharing class EDealerCartUtils {
    
    /**
     * This method will pick the cart items to be displayed for all tabs for a specific dealer
     ***/
    public static List<EDealerCart__c> getCartDetails(Set<Id> cartIDs){
        List<EDealerCart__c> lstEDealerCarts;
        lstEDealerCarts = [SELECT Id, Name, Dealer_Location__c, Dealer_Location__r.Dealer_Code__c,
                           Order_Type__c, Quantity__c, Suggested_Order__c, Suggested_Order__r.Part_Name__c,
                           Suggested_Order__r.Part_Description__c, Suggested_Order__r.Part_Category_Type__c,
                           Suggested_Order__r.Serial_Number__c, Suggested_Order__r.Type__c,
                           Suggested_Order__r.DBS_Type__c, Suggested_Order__r.Is_Special_Order_Part__c,
                           Suggested_Order__r.Pricing_Detail__c, Type__c
                           FROM EDealerCart__c
                           WHERE Id IN :cartIDs];
        return lstEDealerCarts;
    }
    
    /**
     * This method will return the carts details for a specific type
     ***/
    public static List<EDealerCart__c> getCartDetails(Set<Id> cartIDs, String cartType){
        List<EDealerCart__c> lstEDealerCarts;
        if(Schema.sObjectType.EDealerCart__c.fields.Id.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Name.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Dealer_Location__c.isAccessible()
           && Schema.sObjectType.Account.fields.Dealer_Code__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Order_Type__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Quantity__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Suggested_Order__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Name__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Description__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Category_Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Serial_Number__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.DBS_Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Is_Special_Order_Part__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Pricing_Detail__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Type__c.isAccessible()
          ){
              lstEDealerCarts = [SELECT Id, Name, Dealer_Location__c, Dealer_Location__r.Dealer_Code__c, Order_Type__c,
                                 Quantity__c, Suggested_Order__c, Suggested_Order__r.Part_Name__c,
                                 Suggested_Order__r.Part_Description__c, Suggested_Order__r.Part_Category_Type__c,
                                 Suggested_Order__r.Serial_Number__c, Suggested_Order__r.Type__c,
                                 Suggested_Order__r.DBS_Type__c, Suggested_Order__r.Is_Special_Order_Part__c,
                                 Suggested_Order__r.Pricing_Detail__c, Type__c
                                 FROM EDealerCart__c
                                 WHERE Id IN :cartIDs AND Type__c = :cartType];
          }
        return lstEDealerCarts;
    }
    
     
    /**
     * This method will pick the cart items to be displayed for all tabs for a specific dealer
     ***/
    public static List<EDealerCart__c> getCartDetails(string dealerAccountId, set<string> orderTypes, set<string> cartTypes){
        List<EDealerCart__c> lstEDealerCarts;
        if(Schema.sObjectType.EDealerCart__c.fields.Id.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Name.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Dealer_Location__c.isAccessible()
           && Schema.sObjectType.Account.fields.Dealer_Code__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Order_Type__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Quantity__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Suggested_Order__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Name__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Description__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Category_Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Serial_Number__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.DBS_Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Is_Special_Order_Part__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Pricing_Detail__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Type__c.isAccessible()
          ){
              lstEDealerCarts = [SELECT Id, Name, Dealer_Location__c, Dealer_Location__r.Dealer_Code__c, Order_Type__c,
                                 Quantity__c, Suggested_Order__c, Suggested_Order__r.Part_Name__c,
                                 Suggested_Order__r.Part_Description__c, Suggested_Order__r.Part_Category_Type__c,
                                 Suggested_Order__r.Serial_Number__c, Suggested_Order__r.Type__c,
                                 Suggested_Order__r.DBS_Type__c, Suggested_Order__r.Is_Special_Order_Part__c,
                                 Suggested_Order__r.Pricing_Detail__c, Type__c
                                 FROM EDealerCart__c
                                 WHERE Dealer_Location__c = :dealerAccountId
                                 AND Type__c IN :cartTypes
                                 AND Order_Type__c IN :orderTypes];
          }
        
        return lstEDealerCarts;
    }
    
    
    /**
     * This method will used to get the cart items which created for suggested orders
     ***/
    public static List<EDealerCart__c> getCartDetails(Set<Id> soIDs, Set<String> orderTypes, String cartType){
        List<EDealerCart__c> lstEDealerCarts;
        if(Schema.sObjectType.EDealerCart__c.fields.Id.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Name.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Dealer_Location__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Order_Type__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Quantity__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Suggested_Order__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Part_Name__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Type__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Is_Special_Order_Part__c.isAccessible()
           && Schema.sObjectType.EDealer_Suggested_Order__c.fields.Pricing_Detail__c.isAccessible()
           && Schema.sObjectType.EDealerCart__c.fields.Type__c.isAccessible()
          ){
              lstEDealerCarts = [SELECT Id, Name, Dealer_Location__c, Order_Type__c, Quantity__c, Suggested_Order__c,
                Suggested_Order__r.Part_Name__c, Suggested_Order__r.Type__c, Type__c,
                Suggested_Order__r.Is_Special_Order_Part__c, Suggested_Order__r.Pricing_Detail__c
                FROM EDealerCart__c
                WHERE Type__c =:cartType
                AND Order_Type__c IN :orderTypes
                AND Suggested_Order__c IN :soIDs];
          }
        
        return lstEDealerCarts;
    } 

}