force-app/main/default/objects/Account/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <externalId>true</externalId>
    <label>Dealer Code</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PACCARDivision__c.field-meta.xml
<CustomField>
    <fullName>PACCARDivision__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>PacCentral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <formula>Account.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <formula>Account.Dealer_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/EDealer_Tracking__c.object-meta.xml
<CustomObject>
    <label>Gateway Tracking</label>
    <nameField>
        <displayFormat>Track-{000}</displayFormat>
        <label>Gateway Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gateway Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealer_Tracking__c/fields/Kenworth_User_Visited__c.field-meta.xml
<CustomField>
    <fullName>Kenworth_User_Visited__c</fullName>
    <label>Kenworth User Visited</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Last_Logged_In__c.field-meta.xml
<CustomField>
    <fullName>Last_Logged_In__c</fullName>
    <label>Last Logged In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Number_of_User__c.field-meta.xml
<CustomField>
    <fullName>Number_of_User__c</fullName>
    <description>It will store number of users access to edealer dashboard which belong to particular division.</description>
    <label>Number of User</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Number_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Visit__c</fullName>
    <label>Number of Visit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Peterbilt_User_Visited__c.field-meta.xml
<CustomField>
    <fullName>Peterbilt_User_Visited__c</fullName>
    <label>Peterbilt User Visited</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Time_Spent_In_Secs__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_In_Secs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time Spent (In Secs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/Tracking_Details__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Details__c</fullName>
    <label>Tracking Details</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/User_ASI__c.field-meta.xml
<CustomField>
    <fullName>User_ASI__c</fullName>
    <label>User ASI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/User_Division__c.field-meta.xml
<CustomField>
    <fullName>User_Division__c</fullName>
    <label>User Division</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/User_First_Name__c.field-meta.xml
<CustomField>
    <fullName>User_First_Name__c</fullName>
    <label>User First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/User_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Last_Name__c</fullName>
    <label>User Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Tracking__c/fields/User_Primary_Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>User_Primary_Dealer_Code__c</fullName>
    <label>User Primary Dealer Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ASI_Username__c.field-meta.xml
<CustomField>
    <fullName>ASI_Username__c</fullName>
    <label>ASI Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <description>Dealer Code Field Referenced in Community Dashboards Security Predicate</description>
    <formula>Contact.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EdealerTrackingController.cls
/*** 
*   Name        :   edealerTrackingController
*   Description :   This is the apex class which is used for edealerTracking component
*/

public without sharing class  EdealerTrackingController {
    
    /**
*    this is the method which will check if the curent logged in user's activity is already tracked 
*    then increment the count else insert the tracking
*    Example : 
     If user is logged in edealer then we will check if the user is logged in same day then increment the count
     else increase the count and update the record.
**/
    @AuraEnabled
    public static void insertTrackingDetails(String trackingDetail){
        try{
            
            list<EDealer_Tracking__c> lstTracking =[Select id, Number_of_Visit__c ,Number_of_User__c,Tracking_Details__c,Last_Logged_In__c,Kenworth_User_Visited__c 
                                                    ,Peterbilt_User_Visited__c FROM EDealer_Tracking__c WHERE Tracking_Details__c=: trackingDetail 
                                                    and OwnerId =:UserInfo.getUserId() and Last_Logged_In__c = today];
            System.debug('trackingDetail'+trackingDetail);
            System.debug('lstTracking'+lstTracking);
            User usr = [SELECT id,Contact.Account.PACCARDivision__c,Contact.Account.Dealer_Code__c,Profile.Name, 
                        ASI_Username__c FROM user WHERE id =:UserInfo.getUserId()];
            
            // new record creation use case
            if(!lstTracking.isEmpty()){            
                lstTracking[0].Number_of_Visit__c= lstTracking[0].Number_of_Visit__c + 1;
                lstTracking[0].Last_Logged_In__c= system.now();            
                lstTracking[0].User_First_Name__c= UserInfo.getFirstName();
                lstTracking[0].User_Last_Name__c= UserInfo.getLastName();
                lstTracking[0].Username__c= UserInfo.getUserName();
                lstTracking[0].User_Primary_Dealer_Code__c=usr.contact.Account.Dealer_Code__c;
                lstTracking[0].User__c= usr.Profile.Name;
                lstTracking[0].User_Division__c= usr.Contact.Account.PACCARDivision__c;
                lstTracking[0].User_ASI__c= usr.ASI_Username__c;
                if(usr.Contact.Account.PACCARDivision__c =='K'){
                    lstTracking[0].Kenworth_User_Visited__c =lstTracking[0].Kenworth_User_Visited__c+1;
                }else if (usr.Contact.Account.PACCARDivision__c =='P'){
                    lstTracking[0].Peterbilt_User_Visited__c =lstTracking[0].Peterbilt_User_Visited__c+1;
                }
               
                update lstTracking;
            }
            
            // update the existing record use case
            else{
                EDealer_Tracking__c objTracking = new EDealer_Tracking__c();
                objTracking.Number_of_Visit__c = 1;
                
                objTracking.Tracking_Details__c = trackingDetail;
                objTracking.Last_Logged_In__c= system.now();
                objTracking.User_First_Name__c= UserInfo.getFirstName();
                objTracking.User_Last_Name__c= UserInfo.getLastName();
                objTracking.Username__c= UserInfo.getUserName();
                objTracking.User_Primary_Dealer_Code__c=usr.contact.Account.Dealer_Code__c;
                objTracking.User__c= usr.Profile.Name;
                objTracking.User_Division__c= usr.Contact.Account.PACCARDivision__c;
                if(usr.Contact.Account.PACCARDivision__c =='K'){
                    objTracking.Kenworth_User_Visited__c = 1;    
                }else if(usr.Contact.Account.PACCARDivision__c =='P')
                {
                    objTracking.Peterbilt_User_Visited__c = 1;   
                }
                objTracking.User_ASI__c= usr.ASI_Username__c;
                System.debug('objTracking.User_Division__c'+objTracking.User_Division__c);
                
                
                insert objTracking;
            }
        }
        catch(Exception ex){
            EDealerLogUtils.createExceptionLog('EdealerTrackingController'
                                               ,ex.getMessage()
                                               ,ex.getStackTraceString());
            throw new AuraException(ex.getMessage());  
        }
        
    }
    
    @AuraEnabled
    public static void updateTimeSpent(String trackingDetail, Integer timeSpent){
        try{
            
            list<EDealer_Tracking__c> lstTracking =[Select id, Number_of_Visit__c ,Number_of_User__c,Tracking_Details__c,Last_Logged_In__c,Kenworth_User_Visited__c 
                                                    ,Peterbilt_User_Visited__c,Time_Spent_In_Secs__c FROM EDealer_Tracking__c WHERE Tracking_Details__c=: trackingDetail 
                                                    and OwnerId =:UserInfo.getUserId() and Last_Logged_In__c = today];
            System.debug('trackingDetail'+trackingDetail);
            System.debug('lstTracking'+lstTracking);
            User usr = [SELECT id,Contact.Account.PACCARDivision__c,Contact.Account.Dealer_Code__c,Profile.Name, 
                        ASI_Username__c FROM user WHERE id =:UserInfo.getUserId()];
            
            if(!lstTracking.isEmpty()){            
                lstTracking[0].Time_Spent_In_Secs__c= lstTracking[0].Time_Spent_In_Secs__c != null ? 
                lstTracking[0].Time_Spent_In_Secs__c + timeSpent : timeSpent;             
                update lstTracking;
            }
           
        }
        catch(Exception ex){
            EDealerLogUtils.createExceptionLog('EdealerTrackingController'
                                               ,ex.getMessage()
                                               ,ex.getStackTraceString());
            throw new AuraException(ex.getMessage());  
        }
        
    }
}