force-app/main/default/objects/FeatureToggle__mdt/fields/Enabled_For_Users__c.field-meta.xml
<CustomField>
    <fullName>Enabled_For_Users__c</fullName>
    <label>Enabled For Users</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FeatureToggle__mdt/fields/isEnabled__c.field-meta.xml
<CustomField>
    <fullName>isEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FeatureToggleSelector.cls
public without sharing class FeatureToggleSelector {
    public static FeatureToggle__mdt getFeatureToggleByFeatureName(String featureName) {
    FeatureToggle__mdt featureToggle = new FeatureToggle__mdt();
        if( Schema.sObjectType.FeatureToggle__mdt.fields.isEnabled__c.isAccessible()
        && Schema.sObjectType.FeatureToggle__mdt.fields.Enabled_For_Users__c.isAccessible()
           && Schema.sObjectType.FeatureToggle__mdt.fields.DeveloperName.isAccessible()
          ){
              featureToggle = [SELECT Id, DeveloperName, isEnabled__c, Enabled_For_Users__c
                FROM FeatureToggle__mdt
                WHERE DeveloperName = :featureName
                LIMIT 1];
          }       
        return featureToggle;
}
}