force-app/main/default/objects/FeatureToggle__mdt/fields/Enabled_For_Users__c.field-meta.xml
<CustomField>
    <fullName>Enabled_For_Users__c</fullName>
    <label>Enabled For Users</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FeatureToggle__mdt/fields/isEnabled__c.field-meta.xml
<CustomField>
    <fullName>isEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FeatureToggleService.cls
public without sharing class FeatureToggleService {
    private String featureName;

    public FeatureToggleService(String featureName) {
        this.featureName = featureName;
    }
    
    public Boolean isFeaturedEnabled {
        get {
            if (isFeaturedEnabled == null) {
               FeatureToggle__mdt featureToggle = FeatureToggleSelector.getFeatureToggleByFeatureName(featureName);
                if (featureToggle == null || !featureToggle.isEnabled__c) {
                    isFeaturedEnabled = false;
                } else if (featureToggle.isEnabled__c && featureToggle.Enabled_For_Users__c.toLowerCase() == 'all') {
                    isFeaturedEnabled = true;
                } else {
                    String currentUserEmail = UserInfo.getUserEmail();
                    isFeaturedEnabled = featureToggle.Enabled_For_Users__c.containsIgnoreCase(currentUserEmail);
                }
            }
            return isFeaturedEnabled;
        }
        private set;
    }
}