force-app/main/default/objects/eDealer_Config__mdt/eDealer_Config__mdt.object-meta.xml
<CustomObject>
    <label>EDealer Config</label>
    <pluralLabel>EDealer Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/eDealer_Config__mdt/fields/Long_Value__c.field-meta.xml
<CustomField>
    <fullName>Long_Value__c</fullName>
    <label>Long Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/eDealer_Config__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EDealerConfigUtils.cls
public class EDealerConfigUtils {

    public static eDealer_Config__mdt getConfigByDeveloperName(String developerName){
        system.debug('developerName---'+developerName);
        //Get EDealer Config Data
        eDealer_Config__mdt edealerConfig = new eDealer_Config__mdt();
        if( Schema.sObjectType.eDealer_Config__mdt.fields.Long_Value__c.isAccessible()
           && Schema.sObjectType.eDealer_Config__mdt.fields.DeveloperName.isAccessible()
           && Schema.sObjectType.eDealer_Config__mdt.fields.Value__c.isAccessible()
          ){
              edealerConfig = [SELECT Id,DeveloperName, Long_Value__c,Value__c FROM eDealer_Config__mdt WHERE DeveloperName =:developerName];
          }        
        return edealerConfig;
    }
}