force-app/main/default/objects/User/fields/ASI_Username__c.field-meta.xml
<CustomField>
    <fullName>ASI_Username__c</fullName>
    <label>ASI Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <description>Dealer Code Field Referenced in Community Dashboards Security Predicate</description>
    <formula>Contact.Dealer_Code__c</formula>
    <label>Dealer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateOfferPdfController.cls
global with sharing class GenerateOfferPdfController {
    @AuraEnabled
    public static Map<String,List<Map<String,Object>>> getOfferPdfTranslations(String language) {
        return new Map<String,List<Map<String,Object>>>{
            'offerPdfHeader' => LoyaltyMetadataUtility.getTableColumnHeaderTranslations('Offer_Pdfs_Table_Header',language),
                'months' => LoyaltyMetadataUtility.getTableColumnHeaderTranslations('MonthNameTranslations',language)
        };
    }
    
    @AuraEnabled
    public static Map<String, Object> getCurrentLoggedInUserDetails() {
        User currentUser = [SELECT Id, Profile.Name, ASI_Username__c, Name,Dealer_Code__c,contactId
                            FROM User 
                            WHERE Id = :UserInfo.getUserId()
                            LIMIT 1];
        
        Map<String, Object> userDetails = new Map<String, Object>();
        
        if (currentUser != null) {
            userDetails.put('isDealerUser', currentUser.contactId != null);
            userDetails.put('dealerCode', currentUser.Dealer_Code__c);
        }
        
        return userDetails;
    }
    
}