force-app/main/default/objects/Case_Navigation__mdt/Case_Navigation__mdt.object-meta.xml
<CustomObject>
    <label>Case Navigation Item</label>
    <pluralLabel>Case Navigation Items</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Navigation__mdt/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Case Category</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Navigation__mdt/fields/Description_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Description_Custom_Label__c</fullName>
    <description>The custom label name that contains the actual text string to display.</description>
    <label>Description Custom Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Navigation__mdt/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case_Navigation__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Navigation__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Navigation__mdt/fields/Title_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Title_Custom_Label__c</fullName>
    <description>The custom label name that contains the actual text string to display.</description>
    <label>Title Custom Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Navigation_RecordType__mdt/Case_Navigation_RecordType__mdt.object-meta.xml
<CustomObject>
    <label>Case Navigation RecordType</label>
    <pluralLabel>Case Navigation RecordTypes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Navigation_RecordType__mdt/fields/Case_Navigation_Item__c.field-meta.xml
<CustomField>
    <fullName>Case_Navigation_Item__c</fullName>
    <label>Case Navigation Item</label>
    <referenceTo>Case_Navigation__mdt</referenceTo>
    <relationshipLabel>Case Navigation RecordTypes</relationshipLabel>
    <relationshipName>Case_Navigation_RecordTypes</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Case_Navigation_RecordType__mdt/fields/RecordType_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>RecordType_DeveloperName__c</fullName>
    <label>RecordType DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Navigation_RecordType__mdt/fields/Sort_Order_2__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order_2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Navigation_RecordType__mdt/fields/Title_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Title_Custom_Label__c</fullName>
    <description>Custom label name that contains the translated text.</description>
    <label>Title Custom Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDTCaseNavigationDAO.cls
/**
 * @author anthony.beran@slalom.com
 * @date 2019-06-20
 * @version 1.0
 * @description MDTCaseNavigationDAO
 */

public with sharing class MDTCaseNavigationDAO {

    public static List<Case_Navigation__mdt> getByProfile(Set<Id> profileIds) {

        return [
            SELECT Title__c, Case_Category__c, Description__c, Image_Url__c, Sort_Order__c, Title_Custom_Label__c, Description_Custom_Label__c,
            (
                SELECT Title__c, RecordType_DeveloperName__c, Sort_Order_2__c, Title_Custom_Label__c
                FROM Case_Navigation_RecordTypes__r
                WHERE Id IN :profileIds
            )
            FROM Case_Navigation__mdt
            ORDER BY Sort_Order__c ASC
        ];
    }
}