force-app/main/default/objects/Case_Navigation__mdt/Case_Navigation__mdt.object-meta.xml
<CustomObject>
    <label>Case Navigation Item</label>
    <pluralLabel>Case Navigation Items</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Navigation_Profile__mdt/Case_Navigation_Profile__mdt.object-meta.xml
<CustomObject>
    <label>Case Navigation Profile</label>
    <pluralLabel>Case Navigation Profiles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Navigation_Profile__mdt/fields/Case_Navigation_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Case_Navigation_RecordType__c</fullName>
    <label>Case Navigation RecordType</label>
    <referenceTo>Case_Navigation_RecordType__mdt</referenceTo>
    <relationshipLabel>Case Navigation Profiles</relationshipLabel>
    <relationshipName>Case_Navigation_Profiles</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/User/fields/Pass_Group_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Pass_Group_Permissions__c</fullName>
    <label>Pass Group Permissions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
            </value>
            <value>
                <fullName>General Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseCommunityCategoryNavController.cls
/**
 * @author anthony.beran@slalom.com
 * @date 2019-05-12
 * @version 1.0
 * @description CaseCommunityCategoryNavController
 */

public with sharing class CaseCommunityCategoryNavController {

    @AuraEnabled(Cacheable=true)
    public static List<Case_Navigation__mdt> getCaseNavigation() {
        Id userId = UserInfo.getUserId();
        List<User> users = UserDAO.getById(new Set<Id>{userId});

        if ( users.isEmpty() ) {
            DebugLogDomain.log(new LogException('Cant find current logged in user'),  userId, 'CaseCommunityCategoryNavController', 'getCaseNavigation');

            throw new AuraHandledException('An unexpected error happened. Please try again later.');
        }

        Set<Id> caseNavProfileIds = new Set<Id>();
        for ( Case_Navigation_Profile__mdt p : MDTCaseNavigationProfileDAO.getByProfile(new Set<String>{users[0].Profile.Name}) ) {
            caseNavProfileIds.add(p.Case_Navigation_RecordType__c);
        }

        return MDTCaseNavigationDAO.getByProfile(caseNavProfileIds);
    }

    @AuraEnabled (Cacheable=true)
    public static Boolean getVSTileToggle(){
        Boolean displayVS = false;
        User user=EDealerUserUtils.fetchLoggedInUserdetails();
        if(user !=null && user.Pass_Group_Permissions__c !=null && user.Pass_Group_Permissions__c.containsIgnoreCase('Purchasing')){
            displayVS=true;
        }
        return displayVS;
    }
    @AuraEnabled
    public static void getLoggingPermissionSet(){
        List<PermissionSetAssignment> newPSAList = new List<PermissionSetAssignment>();  
        Set<Id> assignedPSAIds = new Set<Id>();
        for(PermissionSetAssignment psa : [Select Id, PermissionSetId from PermissionSetAssignment where AssigneeId=:UserInfo.getUserId()]) {
            assignedPSAIds.add(psa.PermissionSetId);
            system.debug('\n--psa--'+psa);
        }
        EDealerUserUtils.assignConditionalPermissions(new Set<String>(),assignedPSAIds,newPSAList);
        System.debug('newPSAList==>'+newPSAList);
        if(!newPSAList.isEmpty()){
            Database.SaveResult[] results = Database.insert(newPSAList, false);
            EDealerUserUtils.logError(results, 'Insert PermissionSet Assignment from CaseCommunityCategoryNavController');
        }
    }
}