force-app/main/default/objects/EDealer_Relationship__c/EDealer_Relationship__c.object-meta.xml
<CustomObject>
    <label>EDealer Relationship</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>EDealer Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDealer Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealer_Relationship__c/fields/Allow_Download_Of_Reports__c.field-meta.xml
<CustomField>
    <fullName>Allow_Download_Of_Reports__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Download Of Reports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Allow_Upload_Of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Allow_Upload_Of_Orders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Upload Of Orders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Allow_Upload_Of_Rma__c.field-meta.xml
<CustomField>
    <fullName>Allow_Upload_Of_Rma__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Upload Of Rma</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/ASI_Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>ASI_Dealer_Code__c</fullName>
    <label>ASI Dealer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Availability_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Availability_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EDealer Relationships</relationshipLabel>
    <relationshipName>EDealer_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Dealer_Control_Of_Doests__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Control_Of_Doests__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Control Of Doests</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Dealer_Doe_Status__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Doe_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Doe Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Dealer_Group__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Group__c</fullName>
    <label>Dealer Group</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Interactive_Order_Entry__c.field-meta.xml
<CustomField>
    <fullName>Interactive_Order_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interactive Order Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Order_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Order_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Price_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Price_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Return_Inquiry__c.field-meta.xml
<CustomField>
    <fullName>Return_Inquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Return Inquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/Sub_Code__c.field-meta.xml
<CustomField>
    <fullName>Sub_Code__c</fullName>
    <label>Sub Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_Relationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EDealer_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EDealerRelationshipUtil.cls
public with sharing class EDealerRelationshipUtil {
    
    Public static List<EDealer_Relationship__c> getRelationships(Id contactId){
        List<EDealer_Relationship__c> lstRelationships = new List<EDealer_Relationship__c>();
        
        if( Schema.sObjectType.EDealer_Relationship__c.fields.Name.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Contact__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.ASI_Dealer_Code__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Sub_Code__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Customer_Name__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Allow_Download_Of_Reports__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Allow_Upload_Of_Orders__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Allow_Upload_Of_Rma__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Availability_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Dealer_Control_Of_Doests__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Dealer_Doe_Status__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Interactive_Order_Entry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Order_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Price_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Return_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.User__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Division__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Currency_Code__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Dealer_Group__c.isAccessible()
          ){
              lstRelationships = [SELECT Id, Name, Contact__c, ASI_Dealer_Code__c, Sub_Code__c, Customer_Name__c,
                Allow_Download_Of_Reports__c, Allow_Upload_Of_Orders__c, Allow_Upload_Of_Rma__c,
                Availability_Inquiry__c, Dealer_Control_Of_Doests__c, Dealer_Doe_Status__c,
                Interactive_Order_Entry__c, Order_Inquiry__c, Price_Inquiry__c, Return_Inquiry__c,
                User__c, Division__c, Currency_Code__c,country__c,Dealer_Group__c
                FROM EDealer_Relationship__c
                WHERE Contact__c = :contactId Order By ASI_Dealer_Code__c];
          }
        return lstRelationships;
    }
    
    Public static List<EDealer_Relationship__c> getUserRelationships(Id userId){
        system.debug('----userId--' + userId);
        
        List<EDealer_Relationship__c> lstRelationships = new List<EDealer_Relationship__c>();
        if(Schema.sObjectType.EDealer_Relationship__c.fields.Name.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Contact__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.ASI_Dealer_Code__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Sub_Code__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Customer_Name__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Allow_Download_Of_Reports__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Allow_Upload_Of_Orders__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Allow_Upload_Of_Rma__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Availability_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Dealer_Control_Of_Doests__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Dealer_Doe_Status__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Interactive_Order_Entry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Order_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Price_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Return_Inquiry__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.User__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Division__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Currency_Code__c.isAccessible()
           && Schema.sObjectType.EDealer_Relationship__c.fields.Dealer_Group__c.isAccessible()
          ){ 
              lstRelationships = [SELECT Id, Name, Contact__c, ASI_Dealer_Code__c, Sub_Code__c, Customer_Name__c,
                Allow_Download_Of_Reports__c, Allow_Upload_Of_Orders__c, Allow_Upload_Of_Rma__c,
                Availability_Inquiry__c, Dealer_Control_Of_Doests__c, Dealer_Doe_Status__c,
                Interactive_Order_Entry__c, Order_Inquiry__c, Price_Inquiry__c,
                Return_Inquiry__c, User__c, Division__c, Currency_Code__c,country__c,Dealer_Group__c
                FROM EDealer_Relationship__c
                WHERE User__c = :userId Order By ASI_Dealer_Code__c];
          }
        return lstRelationships;
    }

}