force-app/main/default/objects/EDealer_SOF_Summary__c/EDealer_SOF_Summary__c.object-meta.xml
<CustomObject>
    <label>EDealer SOF Summary</label>
    <nameField>
        <displayFormat>Summary-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDealer SOF Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDealer_SOF_Summary__c/fields/Dealer_Code__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Code__c</fullName>
    <label>Dealer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_SOF_Summary__c/fields/Dealer_Divison__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Divison__c</fullName>
    <label>Dealer Divison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDealer_SOF_Summary__c/fields/SOF_Count__c.field-meta.xml
<CustomField>
    <fullName>SOF_Count__c</fullName>
    <label>SOF Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EDealer_SOF_Summary__c/fields/SOF_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>SOF_Date_Time__c</fullName>
    <label>SOF Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EDealer_SOF_Summary__c/fields/Time_of_Day__c.field-meta.xml
<CustomField>
    <fullName>Time_of_Day__c</fullName>
    <label>Time of Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EDealerDeleteOldSOFSummaryBatchTest.cls
@isTest
public class EDealerDeleteOldSOFSummaryBatchTest {
    
    @isTest
    private static void testBatch(){
        
        //Sof Summary 
        EDealer_SOF_Summary__c summary = new EDealer_SOF_Summary__c();
        summary.Dealer_Code__c = 'I080';
        summary.Dealer_Divison__c = 'K';
        summary.SOF_Count__c = 2;
        summary.SOF_Date_Time__c = DateTime.now();
        summary.Time_of_Day__c = 'Day';
        
        insert summary;
        System.assertEquals('I080', [SELECT Dealer_Code__c FROM EDealer_SOF_Summary__c LIMIT 1].Dealer_Code__c, 'Invalid EDealer SOF Summary found.');
        
        Test.setCreatedDate(summary.id, Datetime.now().addDays(-8));
        
        Test.startTest();
        EDealerDeleteOldSOFSummaryBatch objBatch=new EDealerDeleteOldSOFSummaryBatch();
        Id jobid = Database.executeBatch(objBatch);
        String sch = '0 0 3 * * ?'; 
        system.schedule('Test SOF summary delete batch', sch, objBatch); 
        Test.stopTest();
        
        System.assert(jobid != null, 'Job execution is failed.');
    }

}