force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Id</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <description>Exception base cause returned by Exception.getCause</description>
    <label>Cause</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Apex class name</description>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>The relevant data at the time of the error</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number where the exception happened.</description>
    <label>Line Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Apex method name.</description>
    <label>Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>The exception stacktrace if available</description>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The exception type.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Used for logging Debug Log events to get around DML rollback restrictions.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>Store the case id for which logs are created</description>
    <label>Case Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Apex class name.</description>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <label>Created By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Apex method name.</description>
    <label>Method</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Exception name</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugLogDomain.cls
/**
 * @author anthony.beran@slalom.com
 * @date 2019-06-02
 * @version 1.1
 * @description DebugLogDomain - domain class for Debug_Log__c object
 */

public with sharing class DebugLogDomain {
    public static Boolean overrideQueuing = false;

    public class Log {
        public Exception e;
        public String state;
        public String className;
        public String methodName;
        String caseId;
        String user; 
        String status;
        String request;
        String response;

        public Log(Exception e, String state, String className, String methodName) {
            this.e = e;
            this.state = state;
            this.className = className;
            this.methodName = methodName;
        }
        public Log(Id caseId, String user, String status, String request, String response) {
            this.caseId = caseId;
            this.user = user;
            this.status = status;
            this.request = request;
            this.response = response;
        }    
    }

    /**
     * @description Insert new debug log record based on Exception e
     *
     * @param e
     */
    public static void log(Exception e) {
        DebugLogDomain.queueLog(e, '', '', '');
    }

    /**
     * @description Insert new debug log record with state data
     *
     * @param e
     * @param state
     */
    public static void log(Exception e, String state) {
        DebugLogDomain.queueLog(e, state, '', '');
    }

    /**
     * @description Insert new debug log record with state data, class and method name
     *
     * @param e Apex exception class instance
     * @param state the data state at the point of the exception
     * @param className the class where the exception happened
     * @param methodName the method where the exception happened
     */
    public static void log(Exception e, String state, String className, String methodName) {
        DebugLogDomain.queueLog(e, state, className, methodName);
    }
    /**
     * @description create and inserts new debug log record for Eaton Integration.
     */
    public static void log(Id caseId, String user, String status, String request, String response) {
        DebugLogDomain.queueLog(caseId, user, status, request, response);
    }


    /**
     * @description Inserts list of logs
     *
     * @param logs
     */
    public static void log(List<DebugLogDomain.Log> logs) {
        DebugLogDomain.queueLog(logs);
    }

    /**
     * @description returns single Log object that can be used with queueLog. Generally used when logging within a loop to avoid DML governor limits
     *
     * @param e
     * @param state
     * @param className
     * @param methodName
     *
     * @return DebugLogDomain.Log
     */
    public static DebugLogDomain.Log createLog(Exception e, String state, String className, String methodName) {
        return new Log(e, state, className, methodName);
    }

    
    /**
     * @description proxy method for single log events to be pushed to queueLog List
     *
     * @param e
     * @param state
     * @param className
     * @param methodName
     */
    private static void queueLog(Exception e, String state, String className, String methodName) {
        DebugLogDomain.queueLog(new List<DebugLogDomain.Log>{new DebugLogDomain.Log(e, state, className, methodName)});
    }

    private static void queueLog(Id caseId, String user, String status, String request, String response) {
        DebugLogDomain.queueLog(new List<DebugLogDomain.Log>{new DebugLogDomain.Log(caseId, user, status, request, response)});
    }

    /**
     * @description Publishes a new Log Event platform event. Either will publish via a Queue to move the DML operation into a separate context to avoid various mixed DML or rollback DML exceptions. If called from a Queueable context will directly publish instead to avoid hitting the queue child queue governor limit of 1.
     *
     * @param className
     * @param methodName
     * @param e
     * @param state
     */
    private static void queueLog(List<DebugLogDomain.Log> logs) {
        List<Log_Event__e> logEvents = new List<Log_Event__e>();

        for ( DebugLogDomain.Log log : logs ) {
            logEvents.add(new Log_Event__e(
                Class__c = log.className,
                Method__c = log.methodName,
                Message__c = null != log.e ? log.e.getMessage().left(131072): '',
                Stacktrace__c = null != log.e ? log.e.getStackTraceString().left(131072): '',
                Line_Number__c = null != log.e ? log.e.getLineNumber() : null,
                Cause__c = null != log.e ? null != log.e.getCause() ? log.e.getCause().getMessage().left(131072) : '' : '',
                Type__c = null != log.e ? log.e.getTypeName() : '',
                Data__c = null != log.state ? log.state.left(131072) :'',
                Case_Id__c = log.caseId,
                Created_By__c = log.user,
                Status__c = log.status,
                Request_Body__c = log.request,
                Response_Body__c = log.response
            ));
        }

        if ( true == System.isQueueable() || true == DebugLogDomain.overrideQueuing) {
            //since we don't want to hit the child queue limit - just publish instead
            DebugLogDomain.publishLog(logEvents);
        } else {
            System.enqueueJob(new DebugLogQueue(logEvents));
        }
    }

    /**
     * @description Returns new debug log record based on Exception e
     *
     * @param e
     *
     * @return Debug_Log__c
     */
    public static void publishLog(List<Log_Event__e> logs) {

        //log any publishing errors
        List<Database.SaveResult> results = EventBus.publish(logs);

        Integer i = 0;
        for ( Database.SaveResult result : results ) {
            if ( false == result.isSuccess() ) {
                List<Debug_Log__c> debugLogs = new List<Debug_Log__c>();

                for(Database.Error err : result.getErrors()) {
                    debugLogs.add(new Debug_Log__c(
                        Class__c = 'DebugLogDomain',
                        Method__c = 'publishLog',
                        Status__c = String.valueOf(err.getStatusCode()),
                        Message__c = err.getMessage(),
                        Data__c = JSON.serialize(logs[i])
                    ));
                }

                if ( !debugLogs.isEmpty() ) {
                    insert debugLogs;
                }
            }
            i++;
        }
    }

    public static void insertLogs(List<Log_Event__e> logs) {
        List<Debug_Log__c> debugLogs = new List<Debug_Log__c>();

        for ( Log_Event__e log : logs ) {
            debugLogs.add( new Debug_Log__c(
                Class__c = log.Class__c,
                Method__c = log.Method__c,
                Message__c = log.Message__c,
                Stacktrace__c = log.Stacktrace__c,
                Line_Number__c = log.Line_Number__c,
                Cause__c = log.Cause__c,
                Data__c = log.Data__c,
                Type__c = log.Type__c,
                Case_Id__c = log.Case_Id__c,
                Created_By__c = log.Created_By__c,
                Status__c = log.Status__c,
                Request_Body__c = log.Request_Body__c,
                Response_Body__c = log.Response_Body__c
            ));
        }

        if ( !debugLogs.isEmpty() ) {
            insert debugLogs;
        }
    }
    
}